### ISSUE TITLE
i got the error html to png convert

### ISSUE THREAD

**Issue by prashanth759** [thewati/ExtractSatelliteImagesFromCSV#1]
hi my name is prashanth i got error i didn't understand how to resolve it pls can help to solve...
![Screenshot_20221213_044419](https://user-images.githubusercontent.com/95974436/207303486-6f11c287-a08b-4670-9036-82451351d4ba.png)
![main - Jupyter Notebook and 1 more page - Personal - Microsoft​ Edge 13-12-2022 16_44_49](https://user-images.githubusercontent.com/95974436/207303782-53698854-d614-4b35-8163-2e1026cd37e9.png)

**Comment by thewati** [comment]
Did you install the correct Gecko Driver? Verify if you installed the appropriate Gecko Driver for your Operating System. In case you did, you probably also want to verify whether you got the correct release architecture - either 32 bit or 64 bit. If your computer runs on 32 bit, install the 32 bit Gecko driver. Otherwise, install the 64 bit Gecko driver.
